---
# This is to ensure that the nodes reboot automatically if there is a kernel
# panic since this brings the OpenStack API down due to pause frame throttles
- name: Set kernel.panic timeout in sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
    - { name: kernel.panic, value: 5 }
...
