---
# Prepare cluster
- import_playbook: setup.yml

# Setup ceph mount
- import_playbook: manila-client.yml
  when: ceph_mount_share_name is defined

# Add cluster users
- import_playbook: users.yml

# Add admin users
- import_playbook: cluster-admins.yml

# Install monitoring services
- import_playbook: monitoring.yml

# Use mdadm to create software defined raid
- import_playbook: mdadm.yml

# Setup hyperconverged storage. Current clusterfs options are:
# - glusterfs
# - beegfs
# - none
- import_playbook: '{{ cluster_fs }}.yml'

# Cluster login setup
- import_playbook: slurm.yml
...
