---
- src: stackhpc.cluster-infra
- src: stackhpc.monasca-agent
- src: stackhpc.monasca-rsyslog
- src: stackhpc.grafana-conf
- src: stackhpc.gluster-cluster
- src: stackhpc.os-container-infra
- src: stackhpc.os-manila-mount
- src: stackhpc.os-config
- src: singleplatform-eng.users
...